name: release
run-name: "${{ format('release {0}', inputs.bump) }}"

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Bump major, minor, or patch"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Git
        run: |
          git config --global user.email "bot@opencode.ai"
          git config --global user.name "opencode-web-bot"

      - name: Generate route tree
        run: bun x @tanstack/router-cli generate

      - name: Run tests
        run: bun run test

      - name: Run linting
        run: bun run lint

      - name: Type check
        run: bun x tsc --noEmit

      - name: Build and publish NPM package
        env:
          OPENCODE_BUMP: ${{ inputs.bump }}
          OPENCODE_CHANNEL: latest
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Get the version that will be published
          VERSION=$(bun ./script/build-npm.ts 2>&1 | grep "Version synchronization verified" | awk '{print $NF}')
          if [ -z "$VERSION" ]; then
            echo "ERROR: Failed to determine version from build output"
            exit 1
          fi
          echo "Publishing version: $VERSION"

          # Publish to NPM
          bun ./script/publish-npm.ts

          # Create and push git tag
          git config --global user.email "bot@opencode.ai"
          git config --global user.name "opencode-web-bot"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

          echo "Release v$VERSION complete"
